version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mytraining-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Simple123
      MYSQL_DATABASE: MyTraining
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  nextjs:
    build: .
    container_name: nextjs-app
    environment:
      DATABASE_URL: mysql://root:Simple123@mysql:3306/MyTraining
      NEXTAUTH_SECRET: aipd
      NEXTAUTH_URL: http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  mysql-data:
