version: '3.9'

services:
  mysql:
    image: mysql
    container_name: mytraining-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Simple123
      MYSQL_DATABASE: MyTraining
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - mysql

  nextjs-app:
    image: phamducai2009/nextjs-app:latest
    container_name: nextjs-app
    environment:
      DATABASE_URL: mysql://root:Simple123@mytraining-mysql:3306/MyTraining
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  mysql-data:
