version: '3.9'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "sqlserver://db:1433;database=MyTraining;user=sa;password=SimplePassword123;encrypt=true;trustServerCertificate=true"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SimplePassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
